name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Build and push image'
      env:
        TAG: ${{ github.run_number }}
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file src/VacaySoft.Api/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/vacaysoft-api:$TAG
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/vacaysoft-api:${{ jobs.build.env.TAG }}
